In [1]:
from IPython.display import display, HTML
display(HTML("""
<style>
div.container{width:90% !important;}
div.cell.code_cell.rendered{width:100%;}
div.input_prompt{padding:0px;}
div.CodeMirror{font-family:Consolas; font-size:15pt;}
div.text_cell_render.rendered_html{font-size:15pt;}
div.output{font-size:12pt; font-weight:bold;}
div.input{font-family:Consolas; font-size:15pt;}
div.prompt{min-width:70px;}
div#toc-wrapper{padding-top:120px;}
div.text_cell_renderulli{font-size:12pt;padding:5px;}
table.dataframe{font-size:12px;}
</style>
"""))

<b><font size="6" color="red">ch10.  N차원 배열 (Numpy 배열) 다루기 </font></b>

# 4. 복사와 뷰

## 4.1 할당

In [15]:
import numpy as np
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [16]:
b = a

In [17]:
a.shape, a.ndim, id(a), type(a)

((12,), 1, 3116361237968, numpy.ndarray)

In [18]:
b.shape, b.ndim, id(b), type(b)

((12,), 1, 3116361237968, numpy.ndarray)

In [19]:
a == b

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True])

In [20]:
np.all(a==b)

True

In [21]:
b.shape = (3,4) #할당 받은 b의 shape 수정

In [22]:
a.shape, a.ndim, id(a), type(a)

((3, 4), 2, 3116361237968, numpy.ndarray)

In [23]:
b.shape, b.ndim, id(b), type(b)

((3, 4), 2, 3116361237968, numpy.ndarray)

## 4.2 얕은복사 : 뷰(view)

In [25]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [27]:
a.reshape(2,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [29]:
c=a.view()
print(id(a),id(c))

3116391764336 3116365708336


In [30]:
c==a

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [32]:
c.shape=(2,6)
c

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [33]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [37]:
c[1, ::2]=[9,9,9]
c

array([[ 0,  1,  2,  3,  4,  5],
       [ 9,  7,  9,  9,  9, 11]])

In [38]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  9,  7],
       [ 9,  9,  9, 11]])

## 4.3 깊은복사

In [50]:
a = np.array ([[5, 4,15,1],
              [99,6,16,1],
              [20,5,14,0]])
a

array([[ 5,  4, 15,  1],
       [99,  6, 16,  1],
       [20,  5, 14,  0]])

In [56]:
X = a[:,:-1] # 슬라이싱 될 때는 뷰가 반환 (얕은 복사)
X

array([[ 5,  4, 15],
       [99,  6, 16],
       [20,  5, 14]])

In [57]:
X[:, 0] = -9
X

array([[-9,  4, 15],
       [-9,  6, 16],
       [-9,  5, 14]])

In [58]:
X = a[:,:-1].copy() # 깊은 복사
#X =np.array(a[:,:-1],copy=True) # 깊은복사 방법2
X

array([[-9,  4, 15],
       [-9,  6, 16],
       [-9,  5, 14]])

# 5. 고급인덱싱